### ISSUE TITLE
rtree, centerline not installed

### ISSUE THREAD

**Issue by chilieeh** [SpaceNetChallenge/utilities#109]
I am using Ubuntu 16.04 and v3 of this project. When running the utilities package with python 3 (default version when installing python on Ubuntu is 3.6.7), I get the error that the versions are not compatible (package is written in python 2.7 I assume?) just like this:

python3 createDataSpaceNet.py /LabData/AOI_2_Vegas_Roads_Train/
Traceback (most recent call last):
  File "createDataSpaceNet.py", line 4, in <module>
    from spaceNetUtilities import labelTools as lT
  File "/home/marcin/utilities-3.0/python/spaceNetUtilities/labelTools.py", line 381
    print imageId
                ^
SyntaxError: Missing parentheses in call to 'print'

And when I force python 2.7 installation and then switch to python 2.7 I still get the error like this one:

python createDataSpaceNet.py /LabData/AOI_2_Vegas_Roads_Train/
Traceback (most recent call last):
  File "createDataSpaceNet.py", line 4, in <module>
    from spaceNetUtilities import labelTools as lT
  File "/home/marcin/utilities-3.0/python/spaceNetUtilities/labelTools.py", line 4, in <module>
    import geoTools as gT
  File "/home/marcin/utilities-3.0/python/spaceNetUtilities/geoTools.py", line 17, in <module>
    import centerline
ImportError: No module named centerline

I tried installing centerline separately but I would still get an error with rtree/geopandas/osgeo or simply GDAL package.

**Comment by nrweir** [comment]
Hi chilieeh, thanks for moving the issue here.

It looks like you're using the spacenetutilities master branch rather than the "current" version in [the spacenetV3 branch](https://github.com/SpaceNetChallenge/utilities/tree/spacenetV3). I'd recommend re-installing from that branch:

```
git clone https://github.com/spacenetchallenge/utilities.git
git checkout spacenetV3
pip install .
```

The structure of the package has changed a bit between versions, and in spacenetV3 the createDataSpaceNet.py script can be found [here](https://github.com/SpaceNetChallenge/utilities/blob/spacenetV3/spacenetutilities/scripts/createDataSpaceNet.py)

Let me know if you have further questions.

-N
